# Generated by Django 5.0.4 on 2024-04-15 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100, unique=True)),
                ('product_description', models.CharField(blank=True, default='', max_length=500)),
                ('product_price', models.DecimalField(decimal_places=2, default='', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_stock', models.PositiveIntegerField(default='')),
            ],
        ),
    ]
